### ISSUE TITLE
removepower.sh does not remove power after "sudo shutdown -h now" on Raspberry Pi 4B

### ISSUE THREAD

**Issue by jackgit28** [PiSupply/PiPoE#11]
Hi Pi Supply team,

I've found that the Raspberry Pi 4B doesn't have it's power removed by the Pi PoE Hat when shutdown, in the conditions below. Previous generations of Raspberry Pi had their power removed without issue on shutdown.

Logging the issue here following request to do so in a email response after logging it here:
https://uk.pi-supply.com/pages/contact-us

Has new hardware on the Pi 4 prevented the piepoe service and removepower.sh script from powering off the Pi? Can scripts be modified for the Pi 4?

Raspberry Pi used: Model 4B (2GB version)
OS installed: Tried both Desktop and Lite versions of Raspbian (Feb 2020 release)

Steps performed install pipoe service and removepower.sh scripts:
~ $ git clone https://github.com/PiSupply/PiPoE.git
~ $ sudo ./PiPoE/install.sh
~ $ sudo reboot

Then after reboot, tested shutdown with power off with:
~ $ sudo shutdown -h now

Result:
- pipoe service is invoked on shutdown and I believe the removepower.sh script is invoked.
- The Pi 4 shuts down after about 35 seconds, but power remains supplied to the board from the PoE hat.

Desired result:
- Power is removed from the Pi 4 by the PoE hat

Workaround:
The power button on the PoE hat has to be held for 15+ seconds to remove power to the Pi 4.

Any help to fix this appreciated.

**Comment by shawaj** [comment]
@jackgit28 so basically, the pi shuts down, but it still receives power from the PoE HAT?

**Comment by shawaj** [comment]
Also @jackgit28 with the PoE HAT that isn't working on the Pi 4 how you want it to, have you tried that exact board on another version of Pi? I just want to rule out an issue with the firmware on the Atmel chip

**Comment by ChristopherRush** [comment]
@jackgit28 What message did you receive after running `sudo ./PiPoE/install.sh`?

**Comment by ChristopherRush** [comment]
@jackgit28 Is the service running? `sudo systemctl status pipoe.service`

**Comment by ChristopherRush** [comment]
@shawaj @jackgit28 Found the issue. Pi 4 requires a new WiringPi installation - http://wiringpi.com/wiringpi-updated-to-2-52-for-the-raspberry-pi-4b/

**Comment by ryanteck** [comment]
It might be where we need to re-write it if it relys on wiringpi as unfortunately Gordon is no longer maintaining it http://wiringpi.com/wiringpi-deprecated/

**Comment by ChristopherRush** [comment]
Fixed a454360

**Comment by shawaj** [comment]
@ryanteck that might be a good idea to do that then. Can you open a new issue at some point and rework it?

**Comment by jackgit28** [comment]
Thanks @ChristopherRush! Confirmed fixed for me!
