### ISSUE TITLE
Rework to not use wiringPi

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PiPoE#12]
As suggested by @ryanteck in #11 as wiringPi is now deprecated

**Comment by ChristopherRush** [comment]
According to Gordon the latest version is going to be added to the Raspberry Pi repo.

**Comment by tvoverbeek** [comment]
@ChristopherRush Did you contact Gordon?
From his blog post http://wiringpi.com/wiringpi-deprecated/ I get the impression there will be no addition to the Raspberry Pi repo.
His Pi4 compatible deb (version 2.52) is from August last year.
The current version in the repo is still the previous one (not Pi4 compatible).
Also the 2.52 source has not been published by Gordon.

Anyway here is a python implementation of removepower:
```
#!/usr/bin/env python3

import subprocess
import re
import RPi.GPIO as GPIO
from time import sleep

GPIO.setmode(GPIO.BCM)
sysJobTargets = subprocess.check_output(["sudo", "systemctl", "list-jobs"]).decode('utf-8')
if re.search('reboot.target.*start', sysJobTargets) == None:
    GPIO.setup(17, GPIO.OUT)
    GPIO.output(17, GPIO.LOW)
    sleep(30)
```
Needs of course corresponding changes in the service file and the install script.

**Comment by ChristopherRush** [comment]
@tvoverbeek No, I was going off "I’ll push the updated sources shortly. It will hopefully be part of the official release soon, but for now this will do." Didn't spot the date of the post.

**Comment by ChristopherRush** [comment]
Updated 0a8a6a6
