### ISSUE TITLE
Upload Logo

### ISSUE THREAD

**Issue by francesco-vannini** [PiSupply/PiPoE#5]
![pipoe](https://user-images.githubusercontent.com/16068311/30545146-b3dff91c-9c80-11e7-8282-dc3888f70f32.png)

**Comment by francesco-vannini** [comment]
Use this thread to add pictures

**Comment by ChristopherRush** [comment]
![pipoe-github-banner](https://user-images.githubusercontent.com/1878314/73881972-3bc0c600-4859-11ea-84fe-474fa8a54b36.png)
