### ISSUE TITLE
PiJuice and PiPoE

### ISSUE THREAD

**Issue by klint-k** [PiSupply/PiPoE#7]
PiJuice and PiPoE

I would like to know how to install and setup the combination of PiJuice and PiPoE?

**Comment by shawaj** [comment]
What do you want to know? You just attach the Pi PoE on top of the PiJuice, or vice versa, and that's it.

**Comment by ChristopherRush** [comment]
Here is a quick guide - https://learn.pi-supply.com/make/how-to-connect-the-pi-supply-poe-hat-to-the-pijuice/
