### ISSUE TITLE
How to use Pin 17?

### ISSUE THREAD

**Issue by simplexidev** [PiSupply/PiPoE#9]
All of your documentation says to refer here for information about using Pin 17, yet there ceases to be any.

Would love to get a board, but I need to use that pin.

**Comment by ChristopherRush** [comment]
You can see the bash script here - https://github.com/PiSupply/PiPoE/blob/master/removepower.sh 

When you invoke a shutdown the PoE HAT will remove power after 30 seconds for a safe shutdown procedure.

**Comment by simplexidev** [comment]
Thanks @ChristopherRush. That answers my question.
